### PR TITLE
(GH-35) Add per-game styling option

### PR DESCRIPTION
**Pull request by binarystargames**
Styling CSS class injection split into three commits.

### CODE REVIEW

**Review by michaeltlombardi — CHANGES_REQUESTED** [review]
So! Again, this is _rad_. Stoked for this! A few things:

## Commit Change Sets

First, I think we need to edit the second and third commits slightly; The second commit should _only_ have this change:

```html
{{ $injectedClass := partial "platen/getCssClass.html" . }}
<body dir="{{ default "ltr" .Site.Language.LanguageDirection }} class="{{ $injectedClass }}">
```

While that second commit on it's own could never work (because the partial hasn't been defined yet), that will allow us to cherry pick our changes over any updates to the upstream `baseof.html` template.

The third commit then should just be the creation of the partial file which the second commit references.

## Commit Messages

Additionally, if possible, it would be good to edit the commit messages to reflect what/why we're doing this and associate them with #35 now that I've filed it 😅; I suggest:

### Commit 1

```text
(GH-35) Import _default/baseof.html from hugo-book

This commit copies the latest current implementation of the `_default/baseof.html` template
from alex-shpak/hugo-book at the following reference:

https://github.com/alex-shpak/hugo-book/blob/3a65df3a76e20ae3f9926aaa69ffc14a86fff055/layouts/_default/baseof.html

This is in preparation for implementing patches on top of the core template in this project.
```

### Commit 2

```text
(GH-35) Inject CSS into body of _default/baseof.html

This commit modifies the `_default/baseof.html` template to inject
a CSS class into the `body` tag, enabling Platen site maintainers
to override the styling for any page(s) via this mechanism.

This is a patch on top of the `layouts/_default/baseof.html` file
from the usptream project (alex-shpak/hugo-book). If the upstream
file is updated, we will need to replace our copy of the template
with the newer version and then cherry-pick this commit on top.
```

### Commit 3

```text
(GH-35) Implement the getCssClass shortcode

This commit implements a helper shortcode, `getCssClass` to be used in
our patch on the `_default/baseof.html` template to retrieve the class
or classes which should be injected into the `body` of a page.

It defaults to returning an empty string.

In this implementation, If the page is a member of a top-level docs
section (`docs` by default, but can be configured to `games` or anything
else via the `Params.BookSection` parameter in the site config), such as
`content/docs/my_game/rules.md` or `content/games/my_game/rules.md`, then:

1. If the `_index.md` for that section does **not** define `cssClass` in
its frontmatter, then the default CSS class injected for that section is
the URL segment for that section; in this example, `my_game`.
2. If the `_index.md` for that section **does** define `cssClass` in its
frontmatter, then the CSS class injected for that section is the value
of that parameter. This can be used to inject multiple classes, each of
them separated by a single space.

In this current implementation, other top-level pages and sub-sections of
a given section may not override or append their own class injections.
```

I think with these changes we should be good to go for merge!

That will make sure we keep all of the context of the work with the commits and set us up to add automation to keep us in sync with upstream changes in the near future.

**Comment by michaeltlombardi** [comment]
@binarystargames Okay, I reworked the commits as outlined above and verified locally. If you're able to verify implementation on your end, I think we can merge this and call it done!

**Comment by binarystargames** [comment]
Can verify implementation, I tested each of these changes on my site (https://binarystar.games/) and it's currently live with those changes.

**Review by michaeltlombardi — APPROVED** [review]
Manual verification confirmed by both authors.

**Pull request merged**
